# Generated by Django 4.2.2 on 2023-07-27 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(blank=True, max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=700)),
                ('material', models.CharField(blank=True, choices=[('1', 'золотой'), ('2', 'Серебряный'), ('3', 'Жемчуг'), ('4', 'Платина'), ('5', 'Алмаз'), ('6', 'Медь')], max_length=1)),
                ('image', models.ImageField(upload_to='media/products/')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('confirmPassword', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demosite.product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(through='demosite.SelectedProduct', to='demosite.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demosite.product')),
            ],
        ),
        migrations.AddField(
            model_name='selectedproduct',
            name='user_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demosite.usercart'),
        ),
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'unique_together': {('email',)},
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('buyer_message', models.TextField(blank=True, max_length=255)),
                ('selected_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demosite.product')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='selectedproduct',
            unique_together={('user_cart', 'product')},
        ),
    ]
