# Generated by Django 4.2.2 on 2023-06-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0002_registrationform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('description', models.TextField(max_length=700)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
