# Generated by Django 4.2.2 on 2023-07-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0003_usercart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
