# Generated by Django 4.2.2 on 2023-06-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
