# Generated by Django 4.2.2 on 2023-06-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0004_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('1', 'золотой'), ('2', 'Серебряный')], max_length=1),
        ),
    ]
