# Generated by Django 4.2.2 on 2023-08-27 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0005_alter_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('warehouse', 'Warehouse'), ('production', 'Production')], max_length=10)),
                ('destination', models.CharField(choices=[('warehouse', 'Warehouse'), ('production', 'Production')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demosite.product')),
            ],
        ),
    ]
