# Generated by Django 4.2.2 on 2023-07-10 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0006_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=25)),
                ('password1', models.CharField(max_length=25)),
                ('password2', models.CharField(max_length=25)),
            ],
        ),
        # migrations.DeleteModel(
        #     name='Test',
        # ),
        migrations.AddField(
            model_name='buyer',
            name='buyer_message',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='buyer',
            name='selected_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demosite.product'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('1', 'золотой'), ('2', 'Серебряный'), ('3', 'Жемчуг'), ('4', 'Платина'), ('5', 'Алмаз'), ('6', 'Медь')], max_length=1),
        ),
        # migrations.AlterUniqueTogether(
        #     name='registrationform',
        #     unique_together={('email',)},
        # ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demosite.product'),
        ),
    ]
