# Generated by Django 4.2.2 on 2023-08-27 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0007_warehouse_delete_producttransfer'),
    ]


    
