# Generated by Django 4.2.2 on 2023-07-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0007_stock_user_delete_test_buyer_buyer_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('confirmPassword', models.CharField(max_length=25)),
            ],
        ),
    ]
