# Generated by Django 4.2.2 on 2023-07-19 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0008_registerform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
    ]
