# Generated by Django 4.2.2 on 2023-07-23 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0009_rename_password1_user_password_remove_user_password2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterForm',
        ),
    ]
