# Generated by Django 4.2.2 on 2023-07-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0011_registerform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
