# Generated by Django 4.2.2 on 2023-07-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
