# Generated by Django 4.2.2 on 2023-07-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0002_buyer_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='name',
            field=models.CharField(default='Корзина', max_length=100),
        ),
    ]
