# Generated by Django 4.2.2 on 2023-07-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0007_stock_user_delete_test_buyer_buyer_message_and_more'),
    ],

    operations = [
        # migrations.DeleteModel(
        #     name='Test',
        # ),
        
        migrations.AlterUniqueTogether(
            name='registrationform',
            unique_together={('email',)},
        ),
    ]
